spring.application.name=meu-projeto

server.port=8081

spring.profiles.active=test

stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}
stripe.test.secret.key=${STRIPE_TEST_SECRET_KEY}
stripe.public.key=${STRIPE_PUBLIC_KEY}

api.security.token.secret=${JWT_SECRET}